- name: "Print variable"
  debug: var=api_key
- name: "Create FS Store"
  uri:
    url: "http://omserver:8080/api/public/v1.0/admin/backup/snapshot/fileSystemConfigs?pretty=true"
    validate_certs: no
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body: '{"id":"fsstore","assignmentEnabled" : false,"loadFactor" : 50,"mmapv1CompressionSetting" : "GZIP","storePath" : "/data/fsstore","wtCompressionSetting" : "NONE"}'
    status_code: 201
    return_content: yes
    user: admin
    password: "{{api_key}}"
  register: result
- name: "Printing result of API call"
  debug: var=result