- name: "Set variables"
  set_fact:
    confdir: "/root/.config/mongocli"
    conffile: "/root/.config/mongocli/config.toml"

- name: "Install mongocli"
  yum: name=mongocli  state=latest

- name: get automation groupid (projectid)
  shell: mongo omserver.omansible.int:27017 --quiet --eval "print(db.getSiblingDB('mmsdbconfig').config.customers.findOne()._id.str)"
  register: opsmanager_groupid

- name: Creates directory
  file:
    path: '{{ confdir }}'
    state: directory

- name: "Copying mongocli config"
  copy:
    src="mongocli.toml"
    dest='{{ conffile}}'
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
  when: not om_https

- name: "Copying mongocli config (ssl)"
  copy:
    src="mongocli-ssl.toml"
    dest='{{ conffile}}'
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
  when: om_https

- name: update mongocli public key
  lineinfile:
    path: '{{ conffile}}'
    regexp: 'public_api_key'
    line: "  public_api_key = \"{{public_key}}\""

- name: update mongocli private key
  lineinfile:
    path: '{{ conffile}}'
    regexp: 'private_api_key'
    line: "  private_api_key = \"{{private_key}}\""
    
- name: update mongocli project_id
  lineinfile:
    path: '{{ conffile}}'
    regexp: 'project_id'
    line: "  project_id = \"{{opsmanager_groupid.stdout_lines[0]}}\""

- name: Enable monitoring on n1 and n2 via mongocli
  command: /usr/bin/mongocli om monitoring enable {{ item }}
  with_items:
    - n1.omansible.int
    - n2.omansible.int
