---
- name: "Copy mongodb repository files"
  template:
    src="../files/{{mongodb_repo36}}"
    dest="/etc/yum.repos.d/{{mongodb_repo36}}"
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
- name: "Update yum"
  yum: name=* state=latest
- name: "Install MongoDB Enterprise dependencies"
  yum: state=present name={{ item }}
  with_items:
    - cyrus-sasl 
    - cyrus-sasl-gssapi 
    - cyrus-sasl-plain 
    - krb5-libs 
    - libcurl 
    - libpcap 
    - lm_sensors-libs 
    - net-snmp 
    - net-snmp-agent-libs 
    - openldap 
    - openssl 
    - rpm-libs 
    - tcp_wrappers-libs
- name: "Install mongodb"
  yum: name=mongodb-org state=latest
- name: "Create dbpath for Application Database"
  file: path=/data/appdb state=directory mode=0755 owner=mongod group=mongod
- name: "Copy mongod configuration file"
  template: 
    src="../files/mongod.conf"
    dest="/etc/mongod.conf"
    owner=root 
    group=root 
    mode="u=rw,g=r,o=r"
- name: "Enable mongod service"
  service:
    name: mongod
    enabled: yes
- name: "Set SELinux to permissive (will fail and be ignored when running on containers)"
  selinux:
    policy: targeted
    state: permissive
  ignore_errors: yes #Applicable to containers
- name: "Changing SELinux context (will fail and be ignored when running on containers)"
  shell: setenforce 0
  become: yes
  ignore_errors: yes #Applicable to containers
- name: "Start mongod for the Application Database"
  service: name=mongod state=started
  become: yes