# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "node2" do |node2|
    node2.vm.box = "bento/centos-6.6"
    node2.vm.hostname = 'n5'

    node2.vm.network :private_network, ip: "192.168.1.105"
    node2.vm.synced_folder 'shared/',"/home/vagrant/shared", create: true

    node2.vm.network :forwarded_port, guest: 22, host: 33338

    node2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "n5"]
    end
  end
end
